import { RequestService, StatusName } from "@/app/interfaces";


export const mockPendingServices: RequestService[] = [
  {
    id: 1,
    unloadDirection: "Av. Principal 123",
    type: "Entrega Estándar",
    numberPackages: 5,
    country: "Perú",
    department: "Lima",
    district: "Miraflores",
    destination: "Almacén Central",
    unloadLocation: "Lima",
    unloadDate: "2025-03-15",
    distance: 35.2,
    holderName: "Juan Pérez",
    pickupAddress: "Calle Las Flores 456, San Isidro",
    pickupLat: -12.0464,
    pickupLng: -77.0428,
    destinationAddress: "Av. Principal 123, Miraflores",
    destinationLat: -12.1219,
    destinationLng: -77.0297,
    loadDetail: "Productos electrónicos",
    weight: "250kg",
    status: { id: 1, name: StatusName.PENDING },
    statuses: []
  },
  {
    id: 2,
    unloadDirection: "Jr. Los Pinos 789",
    type: "Entrega Urgente",
    numberPackages: 2,
    country: "Perú",
    department: "Lima",
    district: "San Borja",
    destination: "Centro Comercial",
    unloadLocation: "Lima",
    unloadDate: "2025-03-10",
    distance: 28.7,
    holderName: "María García",
    pickupAddress: "Av. Industrial 789, Callao",
    pickupLat: -12.0566,
    pickupLng: -77.1181,
    destinationAddress: "Jr. Los Pinos 789, San Borja",
    destinationLat: -12.1019,
    destinationLng: -76.9975,
    loadDetail: "Documentos confidenciales",
    weight: "10kg",
    status: { id: 1, name: StatusName.PENDING },
    statuses: []
  },
  {
    id: 3,
    unloadDirection: "Av. Arequipa 567",
    type: "Carga Pesada",
    numberPackages: 12,
    country: "Perú",
    department: "Lima",
    district: "Jesús María",
    destination: "Centro de Distribución",
    unloadLocation: "Lima",
    unloadDate: "2025-03-18",
    distance: 42.3,
    holderName: "Carlos Rodríguez",
    pickupAddress: "Av. Argentina 123, Lima",
    pickupLat: -12.0489,
    pickupLng: -77.0946,
    destinationAddress: "Av. Arequipa 567, Jesús María",
    destinationLat: -12.0782,
    destinationLng: -77.0447,
    loadDetail: "Materiales de construcción",
    weight: "1500kg",
    status: { id: 1, name: StatusName.PENDING },
    statuses: []
  }
]; 